coverage_server:
  ros__parameters:
    use_sim_time: False
    default_headland_width: 0.25
    robot_width: 0.7 #0.4
    operation_width: 0.7
    min_turning_radius: 0.35
    linear_curv_change: 200.0
    coordinates_in_cartesian_frame: true
    default_allow_overlap: false
    default_swath_angle_type: "SET_ANGLE"
    default_swath_angle: 0.0 # We know its aligned for the demo
